site_name: My Docs

theme:
  name: "material"
  features:
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

plugins:
  - mkdocstrings

nav:
  - index.md
  - mkdocs_index.md
  - scripts.md
